### ISSUE TITLE
version log

### ISSUE THREAD

**Issue by littlegreenbean33** [vshymanskyy/ViperIDE#17]
Hi,

I was just prompted with new 1.49 version but I see no branch activity in github. ?¿? 

Is there a  version log with improvement from the different versions ?

Thanks. Great work. I have been using it daily for the last 3 weeks and it is a significant efficiency imporvement.

**Comment by vshymanskyy** [comment]
The version log currently not being maintained, as there are a lot of small changes and it's not well-structured. You can see the commit log though

**Comment by vshymanskyy** [comment]
> I have been using it daily for the last 3 weeks and it is a significant efficiency improvement.

Could you please elaborate, what workflow have you been using and what's the improvement?

**Comment by littlegreenbean33** [comment]
Well, instead of editing on my laptop,  downloading, executing.....reset... in my prototyping cycle, I just develop directly on the board using ViperIDE. Out of a click I can soft-reset.  I have a small script that via mpremote downloads my assets back to my computer for version control and snapshots. Nothing extremely sophisticated.

**Comment by brainstorm** [comment]
> Well, instead of editing on my laptop, downloading, executing.....reset... in my prototyping cycle, I just develop directly on the board using ViperIDE. Out of a click I can soft-reset. I have a small script that via mpremote downloads my assets back to my computer for version control and snapshots. Nothing extremely sophisticated.

I second that analysis, ViperIDE is great and I've been recommending it to a few friends! 

I was about to write that `mpremote` script myself (after seeing the discussion in https://github.com/vshymanskyy/ViperIDE/issues/12 and doing it manually for now). I'm a bit disappointed that it needs disconnecting/re-connecting for the sync/copy ops though because Viper-IDE and mpremote have exclusive read access to the board (as expected). @littlegreenbean33, can you share your script and workflow? 

OTOH, I think that a direct integration with [github repository contents API](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28) could be a killer feature to avoid losing recent "local" board/host changes... context: I introduced a change on my board that locked me out completely, even `mpremote cp` didn't work. I had to resort to `esptool.py read_flash ...` to carve out the flash `.py` files with [radare2](https://github.com/radareorg/radare2/) to recover my latest changes from the flash dump.

@vshymanskyy If there was an integration with Github repos API, there would be no need for local filesystem/sync and changes could potentially be staged on save and committed whenever the user wants (even on every X saves, for instance)?

**Comment by vshymanskyy** [comment]
The idea is cool 😎 
But, i'm wondering how the sync could work. In instance, i have a GitHub repo with some files. Now, i'm connecting a device that may have a slightly (or completely) different file system. Which one is correct? Is this device even associated with the repository?
Same applies to regular host filesystem access, if/when it gets implemented.

**Comment by brainstorm** [comment]
Moving this GitHub repo contents idea to a separate issue (don't want to steal this thread): https://github.com/vshymanskyy/ViperIDE/issues/19
